# Generated by Django 5.2.11 on 2026-02-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('likes', models.IntegerField()),
                ('logo_app', models.ImageField(upload_to='media')),
                ('hashtags', models.ManyToManyField(to='hashtags.hashtags')),
            ],
        ),
    ]
