# Generated by Django 5.2.11 on 2026-02-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
