# Generated by Django 5.2.11 on 2026-03-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_app_category'),
        ('category', '0001_initial'),
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['name', 'description'], name='application_name_3acfd7_idx'),
        ),
    ]
