# Generated by Django 5.2.11 on 2026-04-30 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_app_application_name_3acfd7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='likes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
