# Generated by Django 5.2.12 on 2026-06-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_app_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='data_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
