# Generated by Django 5.2.12 on 2026-06-03 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_app_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='app',
            name='likes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
