# Generated by Django 5.2.12 on 2026-06-03 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_rename_data_created_app_date_created_alter_app_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
