# Generated by Django 5.2.11 on 2026-03-07 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_app_application_name_3acfd7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Quantity must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Quantity cannot exceed 5')])),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.app')),
            ],
        ),
    ]
