# Generated by Django 5.2.11 on 2026-04-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_app_likes'),
        ('applications_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreview',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='applications.app'),
        ),
    ]
